"""5.5 Content Generator (the text agent). Fills one slide's slots for
whichever layout it's given -- generalized (M2) across the full 8-layout set,
not just `text_bullets`. Called once per slide: once for the fixed `title`
bookend, once per SlideIntent after the Deck Planner (5.3) + Layout Selector
(5.4) have decided what the deck's content slides are and which layout each
one uses, and (with a caller-supplied, never-LLM-generated value) for the
fixed `closing_contact` bookend. Title and closing stay fixed bookends rather
than planner-decided because the manifest itself says so: `title`'s
`use_when` is "Opening slide of any deck" and `closing_contact`'s is "Final
slide" (Templates/manifest.json) -- every deck needs them regardless of brief
content, so that's a structural guarantee (D3-style), not a narrative choice.

Implements D6: structured outputs (tool-use forcing / JSON-schema mode) +
business-rule validation (the Pydantic-equivalent layer, in
models/slide_spec.py) + one bounded retry that feeds the validation error
back. D6 is provider-agnostic -- generation runs against whichever provider
`llm_providers.call_structured` is pointed at (claude-sonnet-5 is the SDD's
reference model, D6/SS8; Ollama and Gemini are supported swappable
alternatives).

The closing slide's contact block is deliberately NOT generated by the LLM --
real names/emails/phone numbers are exactly the kind of specific fact an LLM
should never invent (see spike FINDINGS.md's fabrication-risk finding). It
comes from the caller (the CLI's --contact flag) instead; see cli.py.
"""
import json

from .llm_providers import call_structured
from .models.slide_spec import SlideSpec, validate_against_layout

SYSTEM_PROMPT_SINGLE_TEMPLATE = """You are the Content Generator for a presentation deck engine (SDD component 5.5).
Given a plain-language brief, produce exactly one '{layout_id}' slide summarizing
what the brief is about, to be used as the {role} of the deck. Respect every
max_chars / max_items / max_chars_per_item / allowed_values constraint below --
these are hard limits, not suggestions. Only fill a slot if you have a
reasonable, brief-grounded answer for it; leave optional slots out rather than
inventing specifics the brief doesn't support.

{layout_id} layout slots:
{slot_desc}
"""


def _describe_slots(layout):
    lines = []
    for slot in layout.non_image_slots():
        bits = [slot.type]
        if slot.required:
            bits.append("required")
        if slot.max_chars:
            bits.append(f"max_chars={slot.max_chars}")
        if slot.max_items:
            bits.append(f"max_items={slot.max_items}")
        if slot.max_chars_per_item:
            bits.append(f"max_chars_per_item={slot.max_chars_per_item}")
        if slot.allowed_values:
            bits.append(f"allowed_values={slot.allowed_values}")
        lines.append(f"- {slot.shape_name} ({', '.join(bits)})")
    return "\n".join(lines)


def _slot_schema_props(layout):
    props, required = {}, []
    for slot in layout.non_image_slots():
        if slot.type == "bullets":
            props[slot.shape_name] = {"type": "array", "items": {"type": "string"}}
        else:
            prop = {"type": "string"}
            if slot.allowed_values:
                prop["enum"] = slot.allowed_values
            props[slot.shape_name] = prop
        if slot.required:
            required.append(slot.shape_name)
    return props, required


def _one_slide_schema(layout):
    props, required = _slot_schema_props(layout)
    return {"type": "object", "properties": props, "required": required, "additionalProperties": False}


def _coerce_dict(value):
    if isinstance(value, dict):
        return value
    if isinstance(value, str):
        try:
            parsed = json.loads(value)
        except json.JSONDecodeError:
            return {}
        return parsed if isinstance(parsed, dict) else {}
    return {}


def generate_single_slide(brief: str, layout, provider: str, model: str, role: str = "opening slide"):
    """Generate exactly one slide for an arbitrary layout -- used for the
    fixed `title` bookend, and per-intent for every content slide once the
    Deck Planner (5.3) + Layout Selector (5.4) have decided the deck's shape.
    D6 contract: schema + business-rule validation + one bounded retry.

    Returns (spec: SlideSpec | None, failure: dict | None) -- exactly one is
    non-None.
    """
    system_prompt = SYSTEM_PROMPT_SINGLE_TEMPLATE.format(
        layout_id=layout.layout_id, role=role, slot_desc=_describe_slots(layout)
    )
    schema = _one_slide_schema(layout)

    raw = _coerce_dict(call_structured(provider, model, system_prompt, brief, schema, "emit_slide"))
    spec = SlideSpec(layout_id=layout.layout_id, content_kind="text", slots=raw)
    errors = validate_against_layout(spec, layout)
    if not errors:
        return spec, None

    retry_prompt = (
        f"Brief: {brief}\n\n"
        f"You previously produced this {layout.layout_id} slide, but it is invalid:\n"
        f"{json.dumps(raw)}\n\nViolations:\n"
        + "\n".join(f"- {e}" for e in errors)
        + "\n\nReturn a corrected version of just this slide."
    )
    try:
        fixed = _coerce_dict(call_structured(provider, model, system_prompt, retry_prompt, schema, "emit_slide"))
        spec2 = SlideSpec(layout_id=layout.layout_id, content_kind="text", slots=fixed)
        errors2 = validate_against_layout(spec2, layout)
        if not errors2:
            return spec2, None
        return None, {"slots": fixed, "errors": errors2}
    except Exception as e:
        return None, {"slots": raw, "errors": errors, "retry_error": str(e)}
